# --- General Settings ---
backend = "glx";
vsync = true;
use-damage = false;
# glx-stencil = false;  # Deprecated
# glx-no-rebind-pixmap = true;  # Deprecated
#
# --- Shadows ---
shadow = true;
shadow-offset-x = 2;
shadow-offset-y = 2;
shadow-radius = 4;
shadow-opacity = 0.25;
crop-shadow-to-monitor = true;
shadow-color = "#1e1e2e";

# --- Fading ---
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;

# --- Blur ---
blur: {
    method = "gaussian";
    strength = 10;
    background = true;
    kernel = "5x5box";
};

# --- Animations ---
animations: (
    {
        triggers = ["open", "show"];
        preset = "appear";
        duration = 0.125;
    },
    {
        triggers = ["close", "hide"];
        preset = "disappear";
        duration = 0.125;
    },
    {
        triggers = ["geometry"];
        scale-x = {
            curve = "cubic-bezier(0.07, 0.65, 0, 1)";
            duration = 0.25;
            start = "window-width-before / window-width";
            end = 1;
        };
        scale-y = {
            curve = "cubic-bezier(0.07, 0.65, 0, 1)";
            duration = 0.25;
            start = "window-height-before / window-height";
            end = 1;
        };
        shadow-scale-x = "scale-x";
        shadow-scale-y = "scale-y";
        offset-x = {
            curve = "cubic-bezier(0.07, 0.65, 0, 1)";
            duration = 0.25;
            start = "window-x-before - window-x";
            end = 0;
        };
        offset-y = {
            curve = "cubic-bezier(0.07, 0.65, 0, 1)";
            duration = 0.25;
            start = "window-y-before - window-y";
            end = 0;
        };
        shadow-offset-x = "offset-x";
        shadow-offset-y = "offset-y";
        saved-image-blend = 0;
    }
);

# --- Rules ---
rules: (
    # Window Types
    { match = "window_type = 'menu'"; shadow = false; background-blur = false; },

    # Specific Windows
    { match = "class_g = 'Polybar'"; shadow = false; blur-background = false; },
    {
        match = "class_g = 'Rofi'";  # App launcher
        shadow = false;
        fade = false;
        blur-background = false;
        animations = (
            {
                triggers = [ "open", "show" ];
                duration = 0;
            },
            {
                triggers = [ "close", "hide" ];
                duration = 0;
            }
        );
    },
    { match = "class_g = 'slop'"; shadow = false; fade = false; blur-background = false; },  # Screenshot utility
    { match = "class_g = 'firefox' && argb"; shadow = false; background-blur = false; },  # Firefox components
    # { match = "name = 'rect-overlay'"; shadow = false; background-blur = false; },  # Screen sharing on teams
);
